apiVersion: v1
kind: Service
metadata:
  name: log-processing-prometheous-service
spec:
  ports:
  # prometheus needs to access /metrics endpoint
  - name: http
    port: 8080
  clusterIP: None
  selector:
    expose_prometheous: "true"