apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexaggregator-logmanagement
  labels:
    app: indexaggregator-logmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexaggregator-logmanagement
  template:
    metadata:
      labels:
        app: indexaggregator-logmanagement
    spec:
      containers:
        - name: indexaggregator
          image: indexaggregator
          imagePullPolicy: Never
          env:
            - name: TOPIC
              value: "persistent://public/default/indexer_aggregator"
            - name: URL_SERVICE
              value: "pulsar://pulsar-mini-proxy:6650"
            - name: FLUSH_TIME
              value: "120000"
            - name: CACHE_SIZE
              value: "100"
            - name: EVICT_PERCENTAGE
              value: "0.75"
            - name: DB_USER
              value: "xviewer "
            - name: DB_PASSWORD
              value: "xviewer"
            - name: MINUTE_DB_TABLE
              value: "facts.xviewer_indexer_metrics_pulsar_mi"
            - name: MINUTE_TABLE_CONSTRAINT
              value: "indexer_metrics_pkey_mi"
            - name: HOUR_DB_TABLE
              value: "facts.xviewer_indexer_metrics_pulsar_h"
            - name: HOUR_TABLE_CONSTRAINT
              value: "indexer_metrics_pkey_h"
            - name: DAY_DB_TABLE
              value: "facts.xviewer_indexer_metrics_pulsar_d"
            - name: DAY_TABLE_CONSTRAINT
              value: "indexer_metrics_pkey_d"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: pulsar-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pulsar-secret
                  key: password