apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricssink-logmanagement
  labels:
    app: metricssink-logmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricssink-logmanagement
  template:
    metadata:
      labels:
        app: metricssink-logmanagement
    spec:
      containers:
        - name: metricssink
          image: metricssink
          imagePullPolicy: Never
          env:
            - name: SINK_TOPIC
              value: "persistent://public/default/metrics_sink"
            - name: URL_SERVICE
              value: "pulsar://pulsar-mini-proxy:6650"