apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricssink-logmanagement
  labels:
    app: metricssink-logmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricssink-logmanagement
  template:
    metadata:
      labels:
        app: metricssink-logmanagement
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: metricssink
          image: metricssink
          imagePullPolicy: Never
          # prometheus needs to access /metrics endpoint
          ports:
          - name: http
            containerPort: 8080
          envFrom:
            - configMapRef:
                name: xviewer-configs
          env:
            - name: SINK_TOPIC
              value: "persistent://public/default/metrics_sink"
            - name: URL_SERVICE
              value: "pulsar://pulsar-mini-proxy:6650"
            - name: BATCH_MAX_MESSAGES
              value: "-1"
            - name: BATCH_TIMEOUT
              value: "100"
            - name: BATCH_MAX_SIZE
              value: "10485760"