apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink-logmanagement
  labels:
    app: sink-logmanagement
    expose_prometheous: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sink-logmanagement
  template:
    metadata:
      labels:
        app: sink-logmanagement
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: sink
          image: sink
          imagePullPolicy: Never
          ports:
          # prometheus needs to access /metrics endpoint
          - name: http
            containerPort: 8080
          envFrom:
            - configMapRef:
                name: xviewer-configs
          env:
            - name: SINK_TOPIC
              value: "persistent://public/default/parsed_logs"
            - name: URL_SERVICE
              value: "pulsar://pulsar-mini-proxy:6650"