apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink-logmanagement
  labels:
    app: sink-logmanagement
    expose_prometheous: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sink-logmanagement
  template:
    metadata:
      labels:
        app: sink-logmanagement
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: sink
          image: sink
          imagePullPolicy: Never
          ports:
          # prometheus needs to access /metrics endpoint
          - name: http
            containerPort: 8080
          - name: jvm
            containerPort: 9000
          envFrom:
            - configMapRef:
                name: xviewer-configs
          env:
            - name: SINK_TOPIC
              value: "persistent://public/default/parsed_logs"
            - name: URL_SERVICE
              value: "pulsar://pulsar-mini-proxy:6650"
        - name: exporter-merger  
          image: quay.io/rebuy/exporter-merger:v0.2.0
          ports:
           - containerPort: 8081
          env:
          # space-separated list of URLs
           - name: MERGER_PORT
             value: "8081"
           - name: MERGER_URLS
             value: http://localhost:9000/metrics http://localhost:8080/metrics
